export const environment = {
  registerUrl: 'http://localhost:8080/api/auth/register',
  loginUrl: 'http://localhost:8080/api/auth/login',
  videoclassesUrl: 'http://localhost:8080/api/videoClasses',
  dictionaryUrl: 'http://localhost:8080/api/dictionary',
  usersUrl: ' http://localhost:8080/api/auth/users',
  userUrl: ' http://localhost:8080/api/auth/me',
  lessonInterestUrl: 'http://localhost:8080/api/lesson-interest',
  addFavoriteUrl: 'http://localhost:8080/api/auth/add-favorite',
  getFavoritesUrl: 'http://localhost:8080/api/auth/favorites',
  paymentUrl: 'http://localhost:8080/api/payments',
  eventUrl: 'http://localhost:8080/api/events',
  reservationUrl: 'http://localhost:8080/api/reservations',
  production: false,
  paypalClientId: '',
};
